name: Deploy Next.js App to S3

on:
  push:
    branches: [ main ]  # Update branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with desired runner OS (e.g., ubuntu-latest)

    steps:
      - uses: actions/checkout@v3  # Checks out your repository code

      - name: Install  App
        run: npm run install
      # Build the Next.js app
      - name: Build Next.js App
        run: npm run build  # Replace with your build command if necessary

      - uses: actions/checkout@main
      - uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks --delete
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-1' 
            SOURCE_DIR: 'public'     
      # Upload the out folder to S3 bucket
      - name: Upload out folder to S3
        run: |
          aws s3 sync out s3://stage-dev/  --delete